In [4]:
import typing as tp
from pathlib import Path

import numpy as np
import pandas as pd

In [3]:
metrics_dir = Path("../../outputs/2022-08-13_11-21-25/GLMVectorizer/agg_metrics")

In [8]:
def prepare_df(file_name: str, rounding: tp.Optional[int] = 1) -> pd.DataFrame:
    file_path = metrics_dir / file_name
    metric_df = pd.read_csv(file_path, sep='\t')
    if rounding is not None:
        metric_df['score'] = metric_df['score'].apply(lambda score: round(score, rounding))
    return metric_df

In [9]:
prepare_df('calinski_harabasz_ARI.tsv')

                   metric  score  hypers                           part
0   calinski_harabasz_ARI   60.2     NaN   russe_bts-rnc-ru-test-public
1   calinski_harabasz_ARI   61.5     NaN  russe_bts-rnc-ru-test-private
2   calinski_harabasz_ARI   55.7     NaN         russe_bts-rnc-ru-train
3   calinski_harabasz_ARI   42.3     NaN              se10-en-semeval10
4   calinski_harabasz_ARI   30.2     NaN                 xl_wsd-zh-test
5   calinski_harabasz_ARI   44.0     NaN                  xl_wsd-zh-dev
6   calinski_harabasz_ARI   41.9     NaN                 xl_wsd-en-test
7   calinski_harabasz_ARI   11.2     NaN                 xl_wsd-ja-test
8   calinski_harabasz_ARI   21.4     NaN                 xl_wsd-sl-test
9   calinski_harabasz_ARI    6.0     NaN                  xl_wsd-sl-dev
10  calinski_harabasz_ARI   21.0     NaN                 xl_wsd-it-test
11  calinski_harabasz_ARI   21.2     NaN                 xl_wsd-bg-test
12  calinski_harabasz_ARI   54.4     NaN                  xl_wsd-bg-dev

In [10]:
prepare_df('silhouette_ARI.tsv')

            metric  score  hypers                           part
0   silhouette_ARI   40.2     NaN   russe_bts-rnc-ru-test-public
1   silhouette_ARI   57.2     NaN  russe_bts-rnc-ru-test-private
2   silhouette_ARI   47.5     NaN         russe_bts-rnc-ru-train
3   silhouette_ARI   38.5     NaN              se10-en-semeval10
4   silhouette_ARI   28.9     NaN                 xl_wsd-zh-test
5   silhouette_ARI   19.3     NaN                  xl_wsd-zh-dev
6   silhouette_ARI   40.2     NaN                 xl_wsd-en-test
7   silhouette_ARI    3.5     NaN                 xl_wsd-ja-test
8   silhouette_ARI   23.7     NaN                 xl_wsd-sl-test
9   silhouette_ARI   -0.5     NaN                  xl_wsd-sl-dev
10  silhouette_ARI   41.0     NaN                 xl_wsd-it-test
11  silhouette_ARI   18.6     NaN                 xl_wsd-bg-test
12  silhouette_ARI   30.3     NaN                  xl_wsd-bg-dev

In [11]:
prepare_df('calinski_harabasz_S10_AVG.tsv')

                       metric  score  hypers                           part
0   calinski_harabasz_S10_AVG   67.2     NaN   russe_bts-rnc-ru-test-public
1   calinski_harabasz_S10_AVG   69.7     NaN  russe_bts-rnc-ru-test-private
2   calinski_harabasz_S10_AVG   65.8     NaN         russe_bts-rnc-ru-train
3   calinski_harabasz_S10_AVG   56.7     NaN              se10-en-semeval10
4   calinski_harabasz_S10_AVG   50.8     NaN                 xl_wsd-zh-test
5   calinski_harabasz_S10_AVG   67.8     NaN                  xl_wsd-zh-dev
6   calinski_harabasz_S10_AVG   59.1     NaN                 xl_wsd-en-test
7   calinski_harabasz_S10_AVG   41.3     NaN                 xl_wsd-ja-test
8   calinski_harabasz_S10_AVG   43.5     NaN                 xl_wsd-sl-test
9   calinski_harabasz_S10_AVG   34.5     NaN                  xl_wsd-sl-dev
10  calinski_harabasz_S10_AVG   41.9     NaN                 xl_wsd-it-test
11  calinski_harabasz_S10_AVG   42.6     NaN                 xl_wsd-bg-test
12  calinski_harabasz_S10_AVG   70.5     NaN                  xl_wsd-bg-dev

In [12]:
prepare_df('silhouette_S10_AVG.tsv')

                metric  score  hypers                           part
0   silhouette_S10_AVG   54.7     NaN   russe_bts-rnc-ru-test-public
1   silhouette_S10_AVG   67.8     NaN  russe_bts-rnc-ru-test-private
2   silhouette_S10_AVG   61.5     NaN         russe_bts-rnc-ru-train
3   silhouette_S10_AVG   54.5     NaN              se10-en-semeval10
4   silhouette_S10_AVG   49.0     NaN                 xl_wsd-zh-test
5   silhouette_S10_AVG   46.6     NaN                  xl_wsd-zh-dev
6   silhouette_S10_AVG   60.6     NaN                 xl_wsd-en-test
7   silhouette_S10_AVG   25.4     NaN                 xl_wsd-ja-test
8   silhouette_S10_AVG   45.8     NaN                 xl_wsd-sl-test
9   silhouette_S10_AVG   25.7     NaN                  xl_wsd-sl-dev
10  silhouette_S10_AVG   63.6     NaN                 xl_wsd-it-test
11  silhouette_S10_AVG   41.3     NaN                 xl_wsd-bg-test
12  silhouette_S10_AVG   44.9     NaN                  xl_wsd-bg-dev